name: My Workflow

on:
  push:
    branches: [main, introducing-subtest]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://golang:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and test
        run: |
          go build ./...
          go test ./...
