name: Lint code

on:
  push:
    branches: [main, introducing-subtest]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - uses: actions/checkout@v3
      - name: install deps
        run: |
          go mod tidy -compat=1.17
          go mod download
  
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2